### ISSUE TITLE
'tw_trace_callback_soap_client_dorequest' should return a value

### ISSUE THREAD

**Issue by KaipiYann** [tideways/homebrew-profiler#1]
Hi,

Tried to install with Homebrew but here is the error I got and don't know what to do.

/bin/sh /private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/libtool --mode=compile clang  -I. -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1 -DPHP_ATOM_INC -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/include -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/main -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1 -I/usr/local/Cellar/php54/5.4.36/include/php -I/usr/local/Cellar/php54/5.4.36/include/php/main -I/usr/local/Cellar/php54/5.4.36/include/php/TSRM -I/usr/local/Cellar/php54/5.4.36/include/php/Zend -I/usr/local/Cellar/php54/5.4.36/include/php/ext -I/usr/local/Cellar/php54/5.4.36/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/tideways.c -o tideways.lo 
mkdir .libs
 clang -I. -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1 -DPHP_ATOM_INC -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/include -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/main -I/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1 -I/usr/local/Cellar/php54/5.4.36/include/php -I/usr/local/Cellar/php54/5.4.36/include/php/main -I/usr/local/Cellar/php54/5.4.36/include/php/TSRM -I/usr/local/Cellar/php54/5.4.36/include/php/Zend -I/usr/local/Cellar/php54/5.4.36/include/php/ext -I/usr/local/Cellar/php54/5.4.36/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/tideways.c  -fno-common -DPIC -o .libs/tideways.o
/private/tmp/php54-tideways20151109-60771-1vevxby/php-profiler-extension-3.0.1/tideways.c:1487:3: error: non-void function 'tw_trace_callback_soap_client_dorequest' should return a value [-Wreturn-type]
                return;
                ^
1 error generated.
make: *** [tideways.lo] Error 1

**Comment by beberlei** [comment]
@KaipiYann fixed, sorry for the inconvenince

**Comment by beberlei** [comment]
Y
