### ISSUE TITLE
Sha 256 mismatch 

### ISSUE THREAD

**Issue by raptor235** [tideways/homebrew-profiler#11]
Getting the following when trying to install any ideas?

Error: SHA256 mismatch
Expected: 8897c04084cdb2e4f5520a70f61113d27cf8a6081d5726f50a71b338ca10c3f9
Actual: a5eeb508d6a71dfcead9c98fb3eeb53587ba342f1eeb52901bdc2a15e71a2829
Archive: /Users/bartdabek/Library/Caches/Homebrew/php71-tideways-v4.1.4.zip
To retry an incomplete download, remove the file above.

**Comment by beberlei** [comment]
Thank you for the report. The homebrew repository is updated manually at the moment, we really need to automate this to get rid of these failures.

**Comment by beberlei** [comment]
Fixed.
