### ISSUE TITLE
tideways.c:34:10: fatal error: 'php.h' file not found

### ISSUE THREAD

**Issue by giroteti** [tideways/homebrew-profiler#7]
brew install php70-tideways
==> Installing php70-tideways from tideways/profiler
==> Downloading https://github.com/tideways/php-profiler-extension/archive/v4.1.4.zip
Already downloaded: /Users/egi/Library/Caches/Homebrew/php70-tideways-v4.1.4.zip
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-tideways/v4.1.4 --with-php-config=/usr/local/opt/php70/bin/php-config
==> make
Last 15 lines from /Users/egi/Library/Logs/Homebrew/php70-tideways/03.make:
mkdir php7/.libs
mkdir .libs
 clang -I. -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4 -DPHP_ATOM_INC -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/include -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/main -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4 -I/usr/local/Cellar/php70/7.0.25_17/include/php -I/usr/local/Cellar/php70/7.0.25_17/include/php/main -I/usr/local/Cellar/php70/7.0.25_17/include/php/TSRM -I/usr/local/Cellar/php70/7.0.25_17/include/php/Zend -I/usr/local/Cellar/php70/7.0.25_17/include/php/ext -I/usr/local/Cellar/php70/7.0.25_17/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/tideways.c  -fno-common -DPIC -o .libs/tideways.o
 clang -I. -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4 -DPHP_ATOM_INC -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/include -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/main -I/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4 -I/usr/local/Cellar/php70/7.0.25_17/include/php -I/usr/local/Cellar/php70/7.0.25_17/include/php/main -I/usr/local/Cellar/php70/7.0.25_17/include/php/TSRM -I/usr/local/Cellar/php70/7.0.25_17/include/php/Zend -I/usr/local/Cellar/php70/7.0.25_17/include/php/ext -I/usr/local/Cellar/php70/7.0.25_17/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/php7/spans.c  -fno-common -DPIC -o php7/.libs/spans.o
/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/php7/spans.c:1:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [php7/spans.lo] Error 1
make: *** Waiting for unfinished jobs....
/private/tmp/php70-tideways-20171128-72970-ecaibw/php-profiler-extension-4.1.4/tideways.c:34:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [tideways.lo] Error 1

**Comment by giroteti** [comment]
On:
MacOs 10.12.6 
php70 from brew
MAMP set up

**Comment by beberlei** [comment]
@giroteti please try with `brew install php70-tideways --env=std` as described in the README.
