### ISSUE TITLE
Mac 10.13.1  Homebrew 1.4.2  brew install php72-tideways error

### ISSUE THREAD

**Issue by pandanrain** [tideways/homebrew-profiler#9]
`==> /usr/local/opt/php72/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php72-tideways/v4.1.4 --with-php-config=/usr/local/opt/php72/bin/php-config
==> make
Last 15 lines from /Users/pandanrain/Library/Logs/Homebrew/php72-tideways/03.make:
mkdir .libs
mkdir php7/.libs
 clang -I. -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4 -DPHP_ATOM_INC -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/include -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/main -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4 -I/usr/local/Cellar/php72/7.2.0_11/include/php -I/usr/local/Cellar/php72/7.2.0_11/include/php/main -I/usr/local/Cellar/php72/7.2.0_11/include/php/TSRM -I/usr/local/Cellar/php72/7.2.0_11/include/php/Zend -I/usr/local/Cellar/php72/7.2.0_11/include/php/ext -I/usr/local/Cellar/php72/7.2.0_11/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/tideways.c  -fno-common -DPIC -o .libs/tideways.o
 clang -I. -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4 -DPHP_ATOM_INC -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/include -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/main -I/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4 -I/usr/local/Cellar/php72/7.2.0_11/include/php -I/usr/local/Cellar/php72/7.2.0_11/include/php/main -I/usr/local/Cellar/php72/7.2.0_11/include/php/TSRM -I/usr/local/Cellar/php72/7.2.0_11/include/php/Zend -I/usr/local/Cellar/php72/7.2.0_11/include/php/ext -I/usr/local/Cellar/php72/7.2.0_11/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/php7/spans.c  -fno-common -DPIC -o php7/.libs/spans.o
/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/php7/spans.c:1:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [php7/spans.lo] Error 1
make: *** Waiting for unfinished jobs....
/private/tmp/php72-tideways-20180111-72554-1ns6wom/php-profiler-extension-4.1.4/tideways.c:34:10: fatal error: 'php.h' file not found
#include "php.h"
         ^~~~~~~
1 error generated.
make: *** [tideways.lo] Error 1
`

**Comment by beberlei** [comment]
Did you run the brew command with `--env=std` like the readme descri bes? this is the error that happens when you don't do it this way, see #5 and #7
